<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Consultas.aspx.cs" Inherits="Prueba_DigitalBank.Paginas.Consultas" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GVListar" runat="server" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateColumns="False" OnRowUpdating="GVListar_RowUpdating" OnRowEditing="GVListar_RowEditing" OnRowDeleting="GVListar_RowDeleting">
  <Columns>
    <asp:TemplateField HeaderText="Id_Usuario">
      <ItemTemplate><%# Eval("id_usuario") %></ItemTemplate>
      <EditItemTemplate><asp:TextBox ID="txtidusu" runat="server" Text='<%# Bind("id_usuario") %>' ReadOnly="true"></asp:TextBox></EditItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Nombres">
      <ItemTemplate><%# Eval("Nombres") %></ItemTemplate>
      <EditItemTemplate><asp:TextBox ID="txtNombres" runat="server" Text='<%# Bind("Nombres") %>'></asp:TextBox></EditItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Fecha_Nacimiento">
      <ItemTemplate><%# Eval("Fecha", "{0:dd-MM-yyyy}") %></ItemTemplate>
      <EditItemTemplate><asp:TextBox ID="txtFechaNacimiento" runat="server" Text='<%# Bind("Fecha", "{0:dd-MM-yyyy}") %>'></asp:TextBox></EditItemTemplate>
    </asp:TemplateField>
    <asp:TemplateField HeaderText="Genero">
      <ItemTemplate><%# Eval("Sexo") %></ItemTemplate>
      <EditItemTemplate><asp:DropDownList ID="ddlGenero" runat="server" SelectedValue='<%# Bind("Sexo") %>'>
        <asp:ListItem Value="M">M</asp:ListItem>
        <asp:ListItem Value="F">F</asp:ListItem>
      </asp:DropDownList></EditItemTemplate>
    </asp:TemplateField>
    
  </Columns>
</asp:GridView>


        </div>
    </form>
</body>
</html>
